In [90]:
import numpy as np
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 4], [1, 5], [2, 6], [3, 7]])

# Bの転置を取り、2つの行列を掛ける
B_transposed = B.T  # Bの形状転置 (4, 2)→(2, 4) へ転置

# AとBの転置の積を計算
multi_array = np.dot(A, B_transposed)

print("---行列の積の計算結果===")
print(multi_array)
print(f"行列の要素の最大値は{multi_array.max()}です。")

---行列の積の計算結果===
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
行列の要素の最大値は47です。
